### ISSUE TITLE
Can't find "class-descriptions-boxable.csv" in 2.5vrd folder

### ISSUE THREAD

**Issue by wisan-dhammatorn** [Yang-Li-2000/Distance-Aware-Occlusion-Detection-with-Focused-Attention#3]
In order to run file "annotations.ipynb", a file "class-descriptions-boxable.csv" is needed to import but I can't find that file in folder ./data/2.5vrd

How can I get that file?

Thank you

**Comment by Yang-Li-2000** [comment]
Hi,

Thanks for your interest in our work.

The file is a part of the OID V4 dataset. It is the "[Class names](https://storage.googleapis.com/openimages/2018_04/class-descriptions-boxable.csv)" file in the "Metadata" of the [OID V4 dataset](https://storage.googleapis.com/openimages/web/download_v4.html).

**Comment by wisan-dhammatorn** [comment]
> Hi,
> 
> Thanks for your interest in our work.
> 
> The file is a part of the OID V4 dataset. It is the "[Class names](https://storage.googleapis.com/openimages/2018_04/class-descriptions-boxable.csv)" file in the "Metadata" of the [OID V4 dataset](https://storage.googleapis.com/openimages/web/download_v4.html).

I appreciate your prompt reply. Your answer helps me solve this problem. Thank you very much.
